github.com:
    users:
        LitFill:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: LitFill
